---
# VLAN 12 Network for Virtual Machines
# This creates a layer 2 VLAN network using the mgmt clusternetwork
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-network
  namespace: default
  labels:
    networks.harvesterhci.io/type: "L2VlanNetwork"
  annotations:
    network.harvesterhci.io/clusternetwork: mgmt
    network.harvesterhci.io/route: '{"mode":"auto","serverIPAddr":"","cidr":"172.16.3.0/24","gateway":"172.16.3.1"}'
    network.harvesterhci.io/vlan-id: "12"
spec:
  config: >-
    {
      "cniVersion": "0.3.1",
      "name": "vm-network",
      "type": "bridge",
      "bridge": "mgmt-br",
      "promiscMode": true,
      "vlan": 12,
      "ipam": {}
    }
